# Generated by Django 3.2.11 on 2022-01-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='registrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.hospitalmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='doctormodel',
            unique_together={('doctor', 'hospital')},
        ),
    ]
