# Generated by Django 3.2.11 on 2022-01-04 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospitalaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalaccess',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
