# Generated by Django 3.2.11 on 2022-01-04 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_hospitalaccess_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalAccess',
            new_name='PatientModel',
        ),
    ]
